### ISSUE TITLE
Replit not working

### ISSUE THREAD

**Issue by bryceworth** [learn-co-curriculum/phase-0-pac-1-programming-with-expressions#7]
### Canvas Link

https://learning.flatironschool.com/courses/5274/pages/programming-with-expressions?module_item_id=349310

### Concern

When I hit "run" in replit, It returns "Hint: hit control+c anytime to enter REPL." 
I got a little bit of help from the chat box support person, saying that the code in the repelit is missing "console.log" but I don't know where its missing that from, where to put it, why its missing, or where/when I need to add it into the code so that  I can actually follow along and learn the information. 

### Additional Context

![Screen Shot 2022-02-04 at 7 44 38 PM](https://user-images.githubusercontent.com/96962223/152627541-9b326c8d-9c24-4a08-8845-bc8356a63813.png)

**Comment by graciemcguire** [comment]
Hi @bryceworth, Thanks for raising this issue!
REPL has recently changed it's structure and the run button no longer works in our lessons. We have now updated these instructions so students can start using the console instead. If you read the lesson in this github repository you will be able to see the reflected changes. The changes might not be reflected in Canvas yet, but they will be for students moving forward. 
I'm going to close this issue for now, but if you feel that I have closed it in error, please feel free to reopen it.
Thanks, and happing coding! 💙
